# Generated by Django 4.0.6 on 2022-08-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='timezone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
