# Generated by Django 4.0.6 on 2022-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_time_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='timezone',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
