# Generated by Django 4.0.6 on 2022-08-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_time_options_alter_time_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
