# Generated by Django 4.0.6 on 2022-08-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_time_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
